In [1]:
import numpy as np

In [14]:
arr1=np.arange(20).reshape(4,5)
arr1

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [28]:
arr1[:,[0,3]]=arr1[:,[3,0]]
arr1

array([[18, 16, 17, 15, 19],
       [ 8,  6,  7,  5,  9],
       [13, 11, 12, 10, 14],
       [ 3,  1,  2,  0,  4]])

In [19]:
#arr1[[0,3],:]=arr1[[3,0],:]
#arr1

In [20]:
arr2=np.array([[1,2,np.nan],[4,5,6],[np.nan,np.nan,9]])
arr2

array([[ 1.,  2., nan],
       [ 4.,  5.,  6.],
       [nan, nan,  9.]])

In [26]:
a=np.nanmean(arr2)
arr2=np.array([[1,2,a],[4,5,6],[a,a,9]])
arr2

array([[1. , 2. , 4.5],
       [4. , 5. , 6. ],
       [4.5, 4.5, 9. ]])

In [2]:
arr3=np.random.randint(low=1,high=100,size=20).reshape(5,4)
arr3

array([[47, 82, 27, 50],
       [52, 88,  3, 19],
       [48, 42, 16, 52],
       [25, 72, 48, 32],
       [46, 88, 32, 78]])

In [41]:
list=[]
for i in range (5):
    for j in range(4):
        if ((arr3[i][j]%3==0) | (arr3[i][j]>25)):
            list.append(arr3[i][j])
list     

[27, 79, 21, 35, 33, 56, 9, 74, 96, 78, 36, 81, 76, 40, 56, 89, 3, 53, 86]

In [4]:
np.percentile(arr3,10)

18.7

In [5]:
np.percentile(arr3,25)

30.75

In [6]:
np.percentile(arr3,50) #percentile (.....,50) also equals to its median 

47.5