In [70]:
#conditions 
#either row=row
#either column=column
#either row & col = row & col
#either row=col & col=row
#either row & col = (1,1) it can broadcast itself to the required shape

In [133]:
def check(arr1,arr2):
    row1=len(arr1)
    col1=len(arr1[0])
    row2=len(arr2)
    col2=len(arr2[0])
    if ((row1==row2) & (col1==col2)):
        
            print("hoga broadcasting")
    
    elif ((col1==col2) & ((row1==1) | (row2==1))):
        
            print("hoga broadcasting")
            
    elif ((row1==row2) & ((col1==1) | (col2==1))):
        
            print("hoga broadcasting")
            
    elif ((row1==1 & col1==1) | (row2==1 & col2==1)):
        
            print("hoga broadcasting")
    
    elif ((row1==col2) & (row2==col1)):
            print("hoga broadcasting")
            
    elif ((row1!=row2) & (col1!=col2)):
        
            print("nahe hoga broadcasting")
            
    
            
    else :
        
            print("Nahe hoga broadcasting")
            
        

In [107]:
import numpy as np

In [99]:
arr1=np.arange(8).reshape(2,4)
arr2=np.arange(8,16).reshape(2,4)

print(arr1)
print(arr2)

[[0 1 2 3]
 [4 5 6 7]]
[[ 8  9 10 11]
 [12 13 14 15]]


In [100]:
check(arr1,arr2)

hoga broadcasting


In [101]:
arr3=np.arange(3).reshape(1,3)
arr4=np.arange(12).reshape(4,3)

print(arr3)
print(arr4)

[[0 1 2]]
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [102]:
check(arr3,arr4)

hoga broadcasting


In [129]:
arr5=np.arange(8).reshape(2,4)
arr6=np.arange(20).reshape(5,4)

print(arr5)
print(arr6)

[[0 1 2 3]
 [4 5 6 7]]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]]


In [130]:
check(arr5,arr6)

Nahe hoga broadcasting


In [152]:
def check2(arr1,arr2):
    try:
      row1=len(arr1[0])
    except :
      row1=1
    try:
       col1=len(arr1)
    except TypeError:
       col1=1
    try:
      row2=len(arr2[0])
    except :
      row2=1
    try:
       col2=len(arr2)
    except TypeError:
       col2=1
    print(row1)
    print(col1)
    print(row2)
    print(col2)
    if ((row1==row2) & (col1==col2)):
        
            print("hoga broadcasting")
    
    elif ((col1==col2) & ((row1==1) | (row2==1))):
        
            print("hoga broadcasting")
            
    elif ((row1==row2) & ((col1==1) | (col2==1))):
        
            print("hoga broadcasting")
            
    elif ((row1==1 & col1==1) | (row2==1 & col2==1)):
        
            print("hoga broadcasting")
    
    elif ((row1==col2) & (row2==col1)):
            print("hoga broadcasting")
            
    elif ((row1!=row2) & (col1!=col2)):
        
            print("nahe hoga broadcasting")
    elif ((col1==row2) & ((row1==1) | (col2==1))):
            print("hoga broadcasting")
            
    elif ((row1==col2) & ((col1==1) | (row2==1))):
            print("hoga broadcasting")
            
    else :
        
            print("Nahe hoga broadcasting")
            
        

In [145]:
arr9=np.arange(3)
arr10=np.arange(9).reshape(3,3)

print(arr9)
print(arr10)

[0 1 2]
[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [146]:
check2(arr9,arr10)

1
3
3
3
hoga broadcasting


In [153]:
arr11 = np.arange(4)
arr12 = np.arange(20).reshape(5,4)
print(arr11)
print(arr12)

[0 1 2 3]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]]


In [154]:
check2(arr11,arr12)

1
4
4
5
nahe hoga broadcasting


In [143]:
arr11+arr12

array([[ 0,  2,  4,  6],
       [ 4,  6,  8, 10],
       [ 8, 10, 12, 14],
       [12, 14, 16, 18],
       [16, 18, 20, 22]])